# Generated by Django 4.2.24 on 2025-09-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('type', models.CharField(blank=True, choices=[('student', 'Студент'), ('postgraduate', 'Аспірант'), ('doctoral', 'Докторант'), ('external', 'Сторонній'), ('staff', 'Співробітник'), ('child', 'Дитина')], max_length=50, null=True, verbose_name='Тип')),
                ('gender', models.CharField(blank=True, choices=[('m', 'ч'), ('f', 'ж')], max_length=50, null=True, verbose_name='Стать')),
                ('full_name', models.CharField(max_length=200, verbose_name='ПІБ студента')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('institute', models.CharField(blank=True, choices=[('ІАДУ', 'ІАДУ'), ('ІАРД', 'ІАРД'), ('ІБІД', 'ІБІД'), ('ІГДГ', 'ІГДГ'), ('ІГСН', 'ІГСН'), ('ІНЕМ', 'ІНЕМ'), ('ІЕСК', 'ІЕСК'), ('ІМІТ', 'ІМІТ'), ('ІПМТ', 'ІПМТ'), ('ІКНІ', 'ІКНІ'), ('ІКТА', 'ІКТА'), ('ІКТЕ', 'ІКТЕ'), ('ІППО', 'ІППО'), ('ІППТ', 'ІППТ'), ('ІМФН', 'ІМФН'), ('ІСТР', 'ІСТР'), ('ІХХТ', 'ІХХТ')], max_length=10, null=True, verbose_name='ННІ')),
                ('course', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], null=True, verbose_name='Курс')),
                ('enrollment_year', models.DateField(blank=True, null=True, verbose_name='Рік вступу')),
                ('graduation_year', models.DateField(blank=True, null=True, verbose_name='Рік закінчення навчання')),
                ('passport_data', models.CharField(blank=True, max_length=50, null=True, verbose_name='Серія та номер паспорта/ID')),
                ('passport_record_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='запис №')),
                ('passport_issue_date', models.DateField(blank=True, null=True, verbose_name='Дата видачі паспорта/ID')),
                ('passport_issued_by', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ким виданий паспорт/ID')),
                ('country', models.CharField(blank=True, default='Україна', max_length=50, null=True, verbose_name='Країна')),
                ('region', models.CharField(blank=True, choices=[('Вінницька', 'Вінницька'), ('Волинська', 'Волинська'), ('Дніпропетровська', 'Дніпропетровська'), ('Донецька', 'Донецька'), ('Житомирська', 'Житомирська'), ('Закарпатська', 'Закарпатська'), ('Запорізька', 'Запорізька'), ('Івано-Франківська', 'Івано-Франківська'), ('Київська', 'Київська'), ('Кіровоградська', 'Кіровоградська'), ('Луганська', 'Луганська'), ('Львівська', 'Львівська'), ('Миколаївська', 'Миколаївська'), ('Одеська', 'Одеська'), ('Полтавська', 'Полтавська'), ('Рівненська', 'Рівненська'), ('Сумська', 'Сумська'), ('Тернопільська', 'Тернопільська'), ('Харківська', 'Харківська'), ('Херсонська', 'Херсонська'), ('Хмельницька', 'Хмельницька'), ('Черкаська', 'Черкаська'), ('Чернівецька', 'Чернівецька'), ('Чернігівська', 'Чернігівська'), ('АР Крим', 'АР Крим')], max_length=50, null=True, verbose_name='Область')),
                ('region_rajon', models.CharField(blank=True, max_length=200, null=True, verbose_name='Район')),
                ('category', models.CharField(blank=True, choices=[('city', 'Місто'), ('urban_settlement', 'Селище міського типу'), ('village', 'Село'), ('settlement', 'Селище')], max_length=50, null=True, verbose_name='Категорія')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Місто')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вулиця')),
                ('dormitory_number', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23')], null=True, verbose_name='Номер гуртожитку')),
                ('room_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер кімнати')),
                ('home_add_country', models.CharField(blank=True, default='Україна', max_length=50, null=True, verbose_name='Країна')),
                ('home_add_region', models.CharField(blank=True, choices=[('Вінницька', 'Вінницька'), ('Волинська', 'Волинська'), ('Дніпропетровська', 'Дніпропетровська'), ('Донецька', 'Донецька'), ('Житомирська', 'Житомирська'), ('Закарпатська', 'Закарпатська'), ('Запорізька', 'Запорізька'), ('Івано-Франківська', 'Івано-Франківська'), ('Київська', 'Київська'), ('Кіровоградська', 'Кіровоградська'), ('Луганська', 'Луганська'), ('Львівська', 'Львівська'), ('Миколаївська', 'Миколаївська'), ('Одеська', 'Одеська'), ('Полтавська', 'Полтавська'), ('Рівненська', 'Рівненська'), ('Сумська', 'Сумська'), ('Тернопільська', 'Тернопільська'), ('Харківська', 'Харківська'), ('Херсонська', 'Херсонська'), ('Хмельницька', 'Хмельницька'), ('Черкаська', 'Черкаська'), ('Чернівецька', 'Чернівецька'), ('Чернігівська', 'Чернігівська'), ('АР Крим', 'АР Крим')], max_length=50, null=True, verbose_name='Область')),
                ('home_add_rajon', models.CharField(blank=True, max_length=200, null=True, verbose_name='Район')),
                ('home_add_category', models.CharField(blank=True, choices=[('city', 'Місто'), ('urban_settlement', 'Селище міського типу'), ('village', 'Село'), ('settlement', 'Селище')], max_length=50, null=True, verbose_name='Категорія')),
                ('home_add_city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Місто')),
                ('home_add_street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вулиця')),
                ('home_add_building', models.CharField(blank=True, max_length=20, null=True, verbose_name='Будинок')),
                ('home_add_apartment', models.CharField(blank=True, max_length=20, null=True, verbose_name='Квартира')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='Дата договору')),
                ('contract_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер договору(не заповнюємо)')),
                ('contract_termination_date', models.DateField(blank=True, null=True, verbose_name='Дата розірвання договору')),
                ('registration_consent', models.BooleanField(default=False, verbose_name='Згода на реєстрацію')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Дата реєстрації прописки')),
                ('registration_dormitory', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23')], null=True, verbose_name='Номер гуртожитку реєстрації')),
                ('deregistration_date', models.DateField(blank=True, null=True, verbose_name='Дата зняття з реєстрації')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примітки')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенти',
            },
        ),
    ]
