# Generated by Django 4.2.24 on 2025-10-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='eviction_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата виселення'),
        ),
        migrations.AddField(
            model_name='student',
            name='settlement_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поселення'),
        ),
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(blank=True, choices=[('city', 'м.'), ('settlement', 'с-ще'), ('village', 'с.'), ('villagesmt', 'смт.')], max_length=50, null=True, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='student',
            name='home_add_category',
            field=models.CharField(blank=True, choices=[('city', 'м.'), ('settlement', 'с-ще'), ('village', 'с.'), ('villagesmt', 'смт.')], max_length=50, null=True, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='student',
            name='institute',
            field=models.CharField(blank=True, choices=[('ІАДУ', 'ІАДУ'), ('ІАРД', 'ІАРД'), ('ІБІБ', 'ІБІБ'), ('ІГДГ', 'ІГДГ'), ('ІГСН', 'ІГСН'), ('ІНЕМ', 'ІНЕМ'), ('ІЕСК', 'ІЕСК'), ('ІМІТ', 'ІМІТ'), ('ІПМТ', 'ІПМТ'), ('ІКНІ', 'ІКНІ'), ('ІКТА', 'ІКТА'), ('ІКТЕ', 'ІКТЕ'), ('ІППО', 'ІППО'), ('ІППТ', 'ІППТ'), ('ІМФН', 'ІМФН'), ('ІСТР', 'ІСТР'), ('ІХХТ', 'ІХХТ')], max_length=10, null=True, verbose_name='ННІ'),
        ),
    ]
