# Generated by Django 4.2.24 on 2025-10-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_category_and_more'),
        ('students', '0003_historicalstudent'),
    ]

    operations = [
    ]
