# Generated by Django 4.2.24 on 2025-11-24 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0004_studentarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Штрафні бали')),
                ('reason', models.TextField(verbose_name='Причина штрафу')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар')),
                ('severity', models.IntegerField(choices=[(1, 'Незначне порушення'), (2, 'Середнє порушення'), (3, 'Серйозне порушення'), (4, 'Критичне порушення')], default=1, verbose_name='Важкість порушення')),
                ('status', models.CharField(choices=[('active', 'Активний'), ('cancelled', 'Скасований'), ('expired', 'Неактивний')], default='active', max_length=20, verbose_name='Статус')),
                ('penalty_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата порушення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата скасування')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='Причина скасування')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_penalties', to=settings.AUTH_USER_MODEL, verbose_name='Ким скасовано')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ким видано')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Штрафний бал',
                'verbose_name_plural': 'Штрафні бали',
                'ordering': ['-penalty_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPenalty',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Штрафні бали')),
                ('reason', models.TextField(verbose_name='Причина штрафу')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар')),
                ('severity', models.IntegerField(choices=[(1, 'Незначне порушення'), (2, 'Середнє порушення'), (3, 'Серйозне порушення'), (4, 'Критичне порушення')], default=1, verbose_name='Важкість порушення')),
                ('status', models.CharField(choices=[('active', 'Активний'), ('cancelled', 'Скасований'), ('expired', 'Неактивний')], default='active', max_length=20, verbose_name='Статус')),
                ('penalty_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата порушення')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата створення')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата скасування')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='Причина скасування')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cancelled_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ким скасовано')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ким видано')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'historical Штрафний бал',
                'verbose_name_plural': 'historical Штрафні бали',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
